### ISSUE TITLE
Confused with the code

### ISSUE THREAD

**Issue by chocolatedesue** [LuckyHookin/edge-TTS-record#3]
dalao，请问这是如何调用edge tts的?

最近想在软件内内嵌一个tts。

我在看其他相关项目，要么用js实现，要么用一个ws接口，但这个好像都不是

能否告知一二？

**Comment by LuckyHookin** [comment]
你好！我用的是浏览器标准 api，也就是 js，只不过我打包封装了起来。如果你对声音的逼真度不感冒，那么 windows 本身就有相应的朗读 api；或者你可以使用像讯飞这些第三方的收费 api。

**Comment by chocolatedesue** [comment]
好的，感谢回复

我还是老老实实用edge的api吧
